/**
 * Voice recordings for the Shadow Mystery activity (public/audio/scenes/shadow/).
 * If you replace a clip with one of a different length, update its durationMs.
 */
export const SHADOW_RECORDINGS = [
  { id: "vo-shadow-la-la-la", folder: "shadow", file: "la-la-la.mp3", lines: ["La la la. Just walking."], durationMs: 4206 },
  { id: "vo-shadow-wait", folder: "shadow", file: "wait.mp3", lines: ["Wait."], durationMs: 993 },
  { id: "vo-shadow-walking-backwards", folder: "shadow", file: "walking-backwards.mp3", lines: ["I'm walking backwards. Nothing can follow me now."], durationMs: 4598 },
  { id: "vo-shadow-keep-following-me", folder: "shadow", file: "keep-following-me.mp3", lines: ["Why does this pigeon keep following me?"], durationMs: 3004 },
  { id: "vo-shadow-can-you-move-me", folder: "shadow", file: "can-you-move-me.mp3", lines: ["Can you move me? Tap where I should go."], durationMs: 3474 },
  { id: "vo-shadow-following-me-again", folder: "shadow", file: "following-me-again.mp3", lines: ["It's following me AGAIN!"], durationMs: 2586 },
  { id: "vo-shadow-copies-everything", folder: "shadow", file: "copies-everything.mp3", lines: ["It copies everything!"], durationMs: 3082 },
  { id: "vo-shadow-still-there", folder: "shadow", file: "still-there.mp3", lines: ["Still there…"], durationMs: 2508 },
  { id: "vo-shadow-you-have-one-too", folder: "shadow", file: "you-have-one-too.mp3", lines: ["Wait… is that YOURS? You have one too?!"], durationMs: 3631 },
  { id: "vo-shadow-make-it-big", folder: "shadow", file: "make-it-big.mp3", lines: ["Can you make it BIG?"], durationMs: 1959 },
  { id: "vo-shadow-closer-to-the-torch", folder: "shadow", file: "closer-to-the-torch.mp3", lines: ["What happens when Milo moves closer to the torch?"], durationMs: 4049 },
  { id: "vo-shadow-mine-got-huge", folder: "shadow", file: "mine-got-huge.mp3", lines: ["Whoa! Mine got HUGE!"], durationMs: 3004 },
  { id: "vo-shadow-huge-again", folder: "shadow", file: "huge-again.mp3", lines: ["HUGE again!"], durationMs: 1646 },
  { id: "vo-shadow-now-its-small", folder: "shadow", file: "now-its-small.mp3", lines: ["Now it's small. What did I do?"], durationMs: 3161 },
  { id: "vo-shadow-what-happened", folder: "shadow", file: "what-happened.mp3", lines: ["What happened?"], durationMs: 1306 },
  { id: "vo-shadow-shadow-waved", folder: "shadow", file: "shadow-waved.mp3", lines: ["My shadow waved too!"], durationMs: 2116 },
  { id: "vo-shadow-wing-down", folder: "shadow", file: "wing-down.mp3", lines: ["Wing down."], durationMs: 1306 },
  { id: "vo-shadow-copycat", folder: "shadow", file: "copycat.mp3", lines: ["It turned around too. Copycat."], durationMs: 3631 },
  { id: "vo-shadow-turned-off-the-sun", folder: "shadow", file: "turned-off-the-sun.mp3", lines: ["Who turned off the sun?!"], durationMs: 3396 },
  { id: "vo-shadow-where-did-you-go", folder: "shadow", file: "where-did-you-go.mp3", lines: ["Shadow? Shadow, where did you go?"], durationMs: 3318 },
  { id: "vo-shadow-cant-see-my-toes", folder: "shadow", file: "cant-see-my-toes.mp3", lines: ["I can't see my toes. Are they still there?"], durationMs: 4754 },
  { id: "vo-shadow-lights-back", folder: "shadow", file: "lights-back.mp3", lines: ["Phew! Light's back… and so is my shadow!"], durationMs: 6034 },
  { id: "vo-shadow-can-hands-make-shadows", folder: "shadow", file: "can-hands-make-shadows.mp3", lines: ["Can HANDS make shadows?"], durationMs: 2769 },
  { id: "vo-shadow-try-with-a-grown-up", folder: "shadow", file: "try-with-a-grown-up.mp3", lines: ["Let's try with a grown-up!"], durationMs: 2116 },
  { id: "vo-shadow-a-light-and-a-wall", folder: "shadow", file: "a-light-and-a-wall.mp3", lines: ["Let's find out. A light and a wall help."], durationMs: 4127 },
  { id: "vo-shadow-shine-a-light", folder: "shadow", file: "shine-a-light.mp3", lines: ["Shine a light at a wall. Put your hands in between."], durationMs: 4284 },
  { id: "vo-shadow-rabbit", folder: "shadow", file: "rabbit.mp3", lines: ["Rabbit! Two fingers up."], durationMs: 2429 },
  { id: "vo-shadow-rabbit-older", folder: "shadow", file: "rabbit-older.mp3", lines: ["Rabbit: make a fist, put two fingers up for ears."], durationMs: 5068 },
  { id: "vo-shadow-bird", folder: "shadow", file: "bird.mp3", lines: ["Bird! Cross your hands and hook your thumbs."], durationMs: 4676 },
  { id: "vo-shadow-bird-older", folder: "shadow", file: "bird-older.mp3", lines: ["Bird: cross your wrists, hook your thumbs, and flap your fingers like wings."], durationMs: 7967 },
  { id: "vo-shadow-dog", folder: "shadow", file: "dog.mp3", lines: ["Dog! Thumb up for an ear. Wiggle the bottom fingers to bark."], durationMs: 6034 },
  { id: "vo-shadow-dog-older", folder: "shadow", file: "dog-older.mp3", lines: ["Dog: thumb up for an ear, two fingers on top, two below. Wiggle the bottom two to open the mouth."], durationMs: 8516 },
  { id: "vo-shadow-my-turn-bird", folder: "shadow", file: "my-turn-bird.mp3", lines: ["My turn. I'll make a bird."], durationMs: 2586 },
  { id: "vo-shadow-a-potato", folder: "shadow", file: "a-potato.mp3", lines: ["That's a potato."], durationMs: 2116 },
  { id: "vo-shadow-a-very-nice-potato", folder: "shadow", file: "a-very-nice-potato.mp3", lines: ["A very nice potato."], durationMs: 2508 },
  { id: "vo-shadow-investigate-shadows", folder: "shadow", file: "investigate-shadows.mp3", lines: ["Want to investigate your own shadows?"], durationMs: 3082 },
  { id: "vo-shadow-make-it-tall", folder: "shadow", file: "make-it-tall.mp3", lines: ["Can you make your shadow TALL?"], durationMs: 2847 },
  { id: "vo-shadow-make-it-tiny", folder: "shadow", file: "make-it-tiny.mp3", lines: ["Can you make it tiny?"], durationMs: 2769 },
  { id: "vo-shadow-shadows-touch", folder: "shadow", file: "shadows-touch.mp3", lines: ["Can your shadows touch?"], durationMs: 2038 },
  { id: "vo-shadow-funny-shadow", folder: "shadow", file: "funny-shadow.mp3", lines: ["Can you make a funny shadow?"], durationMs: 2116 },
  { id: "vo-shadow-make-an-animal", folder: "shadow", file: "make-an-animal.mp3", lines: ["Can you make an animal?"], durationMs: 1802 },
  { id: "vo-shadow-animal-that-moves", folder: "shadow", file: "animal-that-moves.mp3", lines: ["Can you make an animal that moves?"], durationMs: 2586 },
  { id: "vo-shadow-did-it-get-big", folder: "shadow", file: "did-it-get-big.mp3", lines: ["Did your shadow get BIG?"], durationMs: 2351 },
  { id: "vo-shadow-when-bigger", folder: "shadow", file: "when-bigger.mp3", lines: ["When did your shadow get bigger?"], durationMs: 2194 },
  { id: "vo-shadow-funniest-shadow", folder: "shadow", file: "funniest-shadow.mp3", lines: ["Which shadow was the funniest?"], durationMs: 2273 },
  { id: "vo-shadow-high-five-shadow", folder: "shadow", file: "high-five-shadow.mp3", lines: ["Shadow! We did it! High five!"], durationMs: 3553 },
  { id: "vo-shadow-right", folder: "shadow", file: "right.mp3", lines: ["Right."], durationMs: 914 },
] as const;

export type ShadowRecordingId = (typeof SHADOW_RECORDINGS)[number]["id"];
