/**
 * Voice recordings for Milo's World rooms (public/audio/scenes/world/).
 * If you replace a clip with one of a different length, update its durationMs.
 */
export const WORLD_RECORDINGS = [
  { id: "vo-world-pick-a-room", folder: "world", file: "pick-a-room.mp3", lines: ["Pick a room. Any room. (Well — an open one.)"], durationMs: 4911 },
  { id: "vo-world-wonder-whats-behind", folder: "world", file: "wonder-whats-behind.mp3", lines: ["I wonder what's behind there…"], durationMs: 2429 },
  { id: "vo-world-part-of-house-asleep", folder: "world", file: "part-of-house-asleep.mp3", lines: ["Shh. That part of the house is asleep."], durationMs: 3318 },
  { id: "vo-world-teaser-kitchen", folder: "world", file: "teaser-kitchen.mp3", lines: ["I can hear cups behind there…"], durationMs: 2351 },
  { id: "vo-world-teaser-garden", folder: "world", file: "teaser-garden.mp3", lines: ["Is that… grass under the door?"], durationMs: 2586 },
  { id: "vo-world-teaser-washroom", folder: "world", file: "teaser-washroom.mp3", lines: ["Drip… drip… what's in there?"], durationMs: 3553 },
  { id: "vo-world-hello", folder: "world", file: "hello.mp3", lines: ["Hello!"], durationMs: 836 },
  { id: "vo-world-that-tickles", folder: "world", file: "that-tickles.mp3", lines: ["That tickles."], durationMs: 2351 },
  { id: "vo-world-im-a-pigeon", folder: "world", file: "im-a-pigeon.mp3", lines: ["I'm a pigeon. Did you know?"], durationMs: 3239 },
  { id: "vo-world-coo-sorry", folder: "world", file: "coo-sorry.mp3", lines: ["Coo. Sorry. That just comes out."], durationMs: 4833 },
  { id: "vo-world-something-interesting", folder: "world", file: "something-interesting.mp3", lines: ["Something interesting is happening today…"], durationMs: 4441 },
  { id: "vo-world-oh-youre-back", folder: "world", file: "oh-youre-back.mp3", lines: ["Oh! You're back."], durationMs: 1802 },
  { id: "vo-world-was-that-there-yesterday", folder: "world", file: "was-that-there-yesterday.mp3", lines: ["Wait… was that there yesterday?"], durationMs: 2769 },
  { id: "vo-world-lost-something-again", folder: "world", file: "lost-something-again.mp3", lines: ["I've lost something. Again."], durationMs: 2926 },
  { id: "vo-world-funny-shapes-on-the-floor", folder: "world", file: "funny-shapes-on-the-floor.mp3", lines: ["The sun is making funny shapes on the floor…"], durationMs: 3318 },
  { id: "vo-world-my-family-all-round", folder: "world", file: "my-family-all-round.mp3", lines: ["That's my family. We're all round."], durationMs: 3004 },
  { id: "vo-world-very-purple", folder: "world", file: "very-purple.mp3", lines: ["Someone drew me! I look… very purple."], durationMs: 4833 },
  { id: "vo-world-favourite-thing-on-this-wall", folder: "world", file: "favourite-thing-on-this-wall.mp3", lines: ["My favourite thing on this wall."], durationMs: 2273 },
  { id: "vo-world-lamp-knows-something", folder: "world", file: "lamp-knows-something.mp3", lines: ["This lamp looks like it knows something."], durationMs: 2926 },
  { id: "vo-world-something-under-there", folder: "world", file: "something-under-there.mp3", lines: ["Something is under there. I KNOW it."], durationMs: 3161 },
  { id: "vo-world-it-grew", folder: "world", file: "it-grew.mp3", lines: ["It grew! I think. Did it?"], durationMs: 3239 },
  { id: "vo-world-lumpy-bag", folder: "world", file: "lumpy-bag.mp3", lines: ["Whose bag is this? It's very… lumpy."], durationMs: 4127 },
  { id: "vo-world-plane-from-where", folder: "world", file: "plane-from-where.mp3", lines: ["That flew in through the window. From WHERE?"], durationMs: 3396 },
  { id: "vo-world-where-did-that-come-from", folder: "world", file: "where-did-that-come-from.mp3", lines: ["Wait… where did THAT come from?"], durationMs: 2586 },
  { id: "vo-world-kitchen-smell", folder: "world", file: "kitchen-smell.mp3", lines: ["A kitchen! I can smell… something."], durationMs: 3866 },
  { id: "vo-world-dog-was-here", folder: "world", file: "dog-was-here.mp3", lines: ["Dog was here. Everything is slightly moved."], durationMs: 3971 },
  { id: "vo-world-whistle-back", folder: "world", file: "whistle-back.mp3", lines: ["It whistles. I whistle back. We're friends."], durationMs: 4598 },
  { id: "vo-world-so-many-cups", folder: "world", file: "so-many-cups.mp3", lines: ["So many cups. How many, though?"], durationMs: 3631 },
  { id: "vo-world-mmm-ango", folder: "world", file: "mmm-ango.mp3", lines: ["Mmm. Mango. Mmm-ango."], durationMs: 4519 },
  { id: "vo-world-mmmm", folder: "world", file: "mmmm.mp3", lines: ["Mmmm."], durationMs: 1411 },
  { id: "vo-world-splish", folder: "world", file: "splish.mp3", lines: ["Splish. Don't tell Old Cat."], durationMs: 2847 },
  { id: "vo-world-my-reflection", folder: "world", file: "my-reflection.mp3", lines: ["A bird! …Oh. It's my reflection."], durationMs: 3709 },
  { id: "vo-world-cold-in-there", folder: "world", file: "cold-in-there.mp3", lines: ["Cold in there. I checked. Twice."], durationMs: 3239 },
  { id: "vo-world-jar-of-buttons", folder: "world", file: "jar-of-buttons.mp3", lines: ["Squirrel's jar. Full of… buttons?"], durationMs: 3709 },
  { id: "vo-world-hello-sky", folder: "world", file: "hello-sky.mp3", lines: ["Outside! Hello, sky."], durationMs: 2429 },
  { id: "vo-world-snail-moved", folder: "world", file: "snail-moved.mp3", lines: ["Snail moved. A tiny bit."], durationMs: 3396 },
  { id: "vo-world-very-tall-tree", folder: "world", file: "very-tall-tree.mp3", lines: ["A tree! It's very… tall. I'm not."], durationMs: 4598 },
  { id: "vo-world-bird-lives-up-there", folder: "world", file: "bird-lives-up-there.mp3", lines: ["Shh. A bird lives up there."], durationMs: 2691 },
  { id: "vo-world-sun-makes-shadows", folder: "world", file: "sun-makes-shadows.mp3", lines: ["The sun makes shadows. I learned that. Painfully."], durationMs: 4284 },
  { id: "vo-world-snail-made-this", folder: "world", file: "snail-made-this.mp3", lines: ["Leaf, flower, leaf… Snail made this."], durationMs: 4284 },
  { id: "vo-world-dogs-ball", folder: "world", file: "dogs-ball.mp3", lines: ["Dog's ball. Dog is somewhere. Fast."], durationMs: 4206 },
  { id: "vo-world-smell-like-flowers", folder: "world", file: "smell-like-flowers.mp3", lines: ["They smell like… flowers. Obviously."], durationMs: 3788 },
  { id: "vo-world-bath-for-birds", folder: "world", file: "bath-for-birds.mp3", lines: ["A bath for birds. I'm a bird. Hmm."], durationMs: 4911 },
  { id: "vo-world-where-are-the-bubbles", folder: "world", file: "where-are-the-bubbles.mp3", lines: ["Bubbles! Where are the bubbles?"], durationMs: 2586 },
  { id: "vo-world-it-echoes", folder: "world", file: "it-echoes.mp3", lines: ["It echoes in here. HELLO. hello. hello."], durationMs: 4911 },
  { id: "vo-world-handsome-pigeon", folder: "world", file: "handsome-pigeon.mp3", lines: ["Who is that handsome pigeon?"], durationMs: 2351 },
  { id: "vo-world-copies-everything-i-do", folder: "world", file: "copies-everything-i-do.mp3", lines: ["He copies everything I do."], durationMs: 2691 },
  { id: "vo-world-wash-wash-wash", folder: "world", file: "wash-wash-wash.mp3", lines: ["Wash, wash, wash. Wings too."], durationMs: 3082 },
  { id: "vo-world-boat-float", folder: "world", file: "boat-float.mp3", lines: ["Does a paper boat float in here?"], durationMs: 2351 },
  { id: "vo-world-shy-duck", folder: "world", file: "shy-duck.mp3", lines: ["Squeak! He's shy."], durationMs: 2273 },
  { id: "vo-world-socks-all-alone", folder: "world", file: "socks-all-alone.mp3", lines: ["Socks. All alone. Squirrel did this."], durationMs: 4441 },
] as const;

export type WorldRecordingId = (typeof WORLD_RECORDINGS)[number]["id"];
